#!/usr/bin/env python
import os
import sys
import argparse
import platform

sys.path.insert(1, os.path.join(sys.path[0], '..'))

from src.model import Example 


parser = argparse.ArgumentParser(description="""
   This is an example script for running a model from within Docker.""")
parser.add_argument('--output', type=str, default='output.txt',
                    help="""An output file path for our example""")
args = parser.parse_args()

print('Inside Docker using Python version {}'.format(platform.python_version()))
ex_model = Example(args.output)
ex_model.run()
