#!/usr/bin/env python
import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], '..'))

from tests.test_docker_setup import TestDockerSetup

def run_test_python_class():
    ex_model = TestDockerSetup()
    expected_python = ex_model.get_expected_python_version()
    print('Inside Docker using {}'.format(expected_python))

run_test_python_class()
