#!/bin/sh

# Run tests from outside a Docker container using the local environment.
#
# Usage:
#   ./script/test-local

appdir=$(cd $(dirname "$0")/.. && pwd)
export PYTHONPATH="${appdir}/src:$PYTHONPATH"

pytest --durations=5 --disable-warnings --ignore tests/test_docker_setup.py -v tests

